version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
        
      # run tests!
      - run: 
          name: Run tests with coverage
          command: npm test --coverage
      - run:
          name: Deploy application
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  serverless deploy --stage production
              elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                  serverless deploy --stage dev
              fi