import { dbService } from '../services/dbService';
import { ICreateKeyRequest, IReadKeyRequest, IVerifyKeyRequest } from '../interfaces/IRequests';
import { generateID, assignToBody } from '../helper';
import { apiKeyService } from '../services/apiKeyService';
import { AWSError, Lambda } from 'aws-sdk';
import { IApi } from '../interfaces/IApi';
import { responseService } from '../services/responseService';
import { IKey } from '../interfaces/IKey';
export class ApiKey {
    private DATABASE_ID = 'apiKey';

    /**
     * This is a function to create an API Key
     *
     * @memberof ApiKey
     */
    create = async (createKeyRequest: ICreateKeyRequest): Promise<object> => {
        try {
            let response;
            const db: dbService = new dbService(this.DATABASE_ID);
            // Generate the item to be stored in the db
            const item = {
                // The ID is generated by concatenating the cognitoUsername and apiId
                id: generateID(createKeyRequest.cognitoUsername, createKeyRequest.apiId),
                cognitoUsername: createKeyRequest.cognitoUsername,
                apiID: createKeyRequest.apiId,
                email: createKeyRequest.email,
                apiKey: apiKeyService.create(),
                createdAt: Date.now(),
                verified: false,
                last_accessed: Date.now()
            };

            await db.putItem(item)
                .then((data) => {
                    response = assignToBody({
                        message: 'Your Key has been created'
                    });
                })
                .catch((error: AWSError) => {
                    throw new Error(error.message)
                });
            return response;
        } catch (error) {
            throw new Error(error.message)
        }
    }

    /**
     * This is function to refresh the API token
     *
     * @memberof ApiKey
     */
    refresh = async (createKeyRequest: ICreateKeyRequest) => {
        try {
            let response;
            const id = generateID(createKeyRequest.cognitoUsername, createKeyRequest.apiId);
            const db: dbService = new dbService(this.DATABASE_ID);

            await db.update(id, {
                apiKey: apiKeyService.create(),
                createdAt: Date.now(),
                last_accessed: Date.now()
            })
                .then((data) => {
                    response = assignToBody({
                        message: 'Your key has been refreshed'
                    });
                })
                .catch((error) => {
                    throw new Error(error.message);
                });
            return response;
        } catch (error) {
            throw new Error(error.message);
        }
    }

    /**
     * This is a function to update the last_accessed key in dynamoDB
     * after a user attempts to
     *
     * @memberof ApiKey
     */
    updateLastAccessed = async (id) => {
        try {
            let response;
            const db: dbService = new dbService(this.DATABASE_ID);

            await db.update(id, {
                last_accessed: Date.now()
            })
                .then((data) => {
                    response = assignToBody({
                        message: 'last_accessed key was successfully updated'
                    });
                    console.log(data);
                })
                .catch((error) => {
                    console.log(error)
                    throw new Error(error.message);
                });

            return response;
        } catch (error) {
            throw new Error(error.message);
        }
    }

    /**
     *
     *
     * @memberof ApiKey
     */
    readSingle = async (readKeyRequest: IReadKeyRequest) => {
        try {
            let response;
            const db: dbService = new dbService(this.DATABASE_ID);
            const id: string = generateID(readKeyRequest.cognitoUsername, readKeyRequest.apiId);

            await db.getItem(id)
                .then((data) => {
                    response = assignToBody({
                        apiKey: data.Item.apiKey,
                        verified: data.Item.verified
                    });
                })
                .catch((error: AWSError) => {
                    throw new Error(error.message);
                });
            return response;
        } catch (error) {
            throw new Error(error.message)
        }
    }

    /**
     *
     *
     * @memberof ApiKey
     */
    readAllForUser = async (cognitoUsername: string) => {
        try {
            let _response;
            const db: dbService = new dbService(this.DATABASE_ID);
            const params = {
                cognitoUsername: cognitoUsername
            };
            await db.scan(params)
                .then((data) => {
                    _response = data.Items;
                })
                .catch((error) => {
                    console.log(error);
                    throw new Error(error.message);
                });

            _response = await Promise.all(_response.map(async (item) => {
                let api: IApi;
                const apiDB: dbService = new dbService("api");
                await apiDB.getItem(item['apiID'])
                    .then((data) => {
                        api = data.Item;
                    })
                    .catch((error) => {
                        throw new Error(error.message);
                    })

                if (api) {
                    return {
                        api: api,
                        apiKey: item['apiKey'],
                        verified: item['verified']
                    }
                } else {
                    return null;
                }
            }));

            _response = _response.filter((item) => {
                return item !== null;
            });

            return responseService.success(_response);
        } catch (error) {
            return responseService.error(error.message, error.statusCode);
        }
    }

    /**
     *
     *
     * @memberof ApiKey
     */
    readAllUnverified = async () => {
        try {
            let response;
            const db: dbService = new dbService(this.DATABASE_ID);
            const params = {
                verified: false
            };
            await db.scan(params)
                .then((data) => {
                    const items = data.Items.map((item) => {
                        return {
                            email: item['email'],
                            apiID: item['apiID'],
                            verified: item['verified'],
                            cognitoUsername: item['cognitoUsername']
                        };
                    });
                    response = assignToBody(items);
                })
                .catch((error) => {
                    console.log(error);
                });
            return response;
        } catch (error) {
            throw new Error(error.message)
        }
    }

    /**
     *
     *
     * @memberof ApiKey
     */
    verify = async (verifyKeyRequest: IVerifyKeyRequest) => {
        try {
            let response;
            const db: dbService = new dbService(this.DATABASE_ID);
            const id: string = generateID(verifyKeyRequest.cognitoUsername, verifyKeyRequest.apiId);
            const params = {
                verified: true
            };
            await db.update(id, params)
                .then((data) => {
                    response = {
                        body: data.Attributes
                    };
                })
                .catch((error) => {
                    throw new Error(error.message);
                });
            return response;
        } catch (error) {
            throw new Error(error.message)
        }

    }

    authorise = async (apiKey: string, apiID: string, methodArn: string) => {
        try {
            let policy;
            let key: IKey;
            const db: dbService = new dbService(this.DATABASE_ID);
            const params = {
                apiKey: apiKey,
                apiID: apiID
            };

            await db.scan(params).then((data) => {
                key = data.Items[0];
            }).catch((error) => {
                throw new Error(error.message);
            });
            console.log(key);
            if (key.verified) {
                policy = apiKeyService.generatePolicy(key.cognitoUsername, "Allow", methodArn)
            } else {
                policy = apiKeyService.generatePolicy(key.cognitoUsername, "Deny", methodArn)
            }
            console.log(policy);
            return policy;
        } catch (error) {
            console.log(error);
            return apiKeyService.generatePolicy('user', "Deny", methodArn)
        }
    }

}